apiVersion: apps/v1
kind: Deployment
metadata:
  name: wb-worker-deployment
  namespace: workers
  labels:
    app: wb-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wb-worker
  template:
    metadata:
      labels:
        app: wb-worker
    spec:
      containers:
      - name: worker-node        
        image: sa-saopaulo-1.ocir.io/idhkis4m3p5e/prd01worker-kubernetes:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 50m
            memory: 2Gi
          requests:
            cpu: 50m
            memory: 2Gi
        env:
          - name: REACT_APP_API_HOST
            valueFrom:
              configMapKeyRef:
                name: wb-worker-config
                key: wb-api-host
          - name: REACT_APP_TLS
            valueFrom:
              configMapKeyRef:
                name: wb-worker-config
                key: wb-api-tls
      imagePullSecrets:
        - name: ocirsecret

